# Change these first
owner: actionstatuspage # Your GitHub organization or username, where this repository lives
repo: actionstatuspage # The name of this repository

sites:
  - name: Action Sales
    url: https://app.actionsales.com.ar
  - name: Action Route
    url: https://route.actionsales.com.ar
  - name: Action Api
    url: https://api.actionsales.com 

status-website:
  
  baseUrl: /actionstatuspage

  logoUrl: https://www.actionsales.com.ar/img/logo-action.svg

  introTitle: "En esta web se puede verificar los servicios de Action Sales"
  name: "" 

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
